{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-2.7.5-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7.5-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7.5-SNAPSHOT.jar",
          "size": 421432,
          "sha512": "438a50e10cf14446409b31084c05b177bd5761891ce744e41583e99dc865cd22ed505bc04ff877c6002f4f347a6e32caf8314d7b06e647132a212583a0c7e554",
          "sha256": "2ccf3826c1d7c836c093c2401bcab350955c890812351d109f115f4469529b91",
          "sha1": "ccef35758dcfc84ce50b38c04ef75948e109bb15",
          "md5": "d4cea46a6f2fd8ff1204a68cf8ad6d45"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7.5-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7.5-SNAPSHOT.jar",
          "size": 421432,
          "sha512": "438a50e10cf14446409b31084c05b177bd5761891ce744e41583e99dc865cd22ed505bc04ff877c6002f4f347a6e32caf8314d7b06e647132a212583a0c7e554",
          "sha256": "2ccf3826c1d7c836c093c2401bcab350955c890812351d109f115f4469529b91",
          "sha1": "ccef35758dcfc84ce50b38c04ef75948e109bb15",
          "md5": "d4cea46a6f2fd8ff1204a68cf8ad6d45"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7.5-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7.5-SNAPSHOT-sources.jar",
          "size": 186546,
          "sha512": "06ec2b794da52dd05c9b1e174e7801b3eb537367f6250133a5bd9b6e1b5810b8c64809efc9a328adcccc057660ac057df045b557b9923ac3bfd33d135338b070",
          "sha256": "4f36344b0e33d4d95c00497d9622d0c1cb575228ec83388dbb3f53092139bf10",
          "sha1": "c555585604a20bf8a4b7fb7c635d4bc2bfd3431c",
          "md5": "1b1a8abda3d75ace390a318dce0c9f01"
        }
      ]
    }
  ]
}
