{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7.4-SNAPSHOT/snakeyaml-engine-kmp-2.7.4-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp.klib",
          "url": "snakeyaml-engine-kmp-mingwx64-2.7.4-SNAPSHOT.klib",
          "size": 424619,
          "sha512": "fedf19662072b0f9fd6492c36d877c6d1bdc51b0107cebadf0d4be669164be38fccee2197ffdaebe66fef908c50994a257d39a68cb2c09ded821ce84b7e9cf7e",
          "sha256": "4fb29ded02a2b2b2f8ef8709939cda6a2ee8cba6cc7e8e8154565c44caefe24a",
          "sha1": "8ad486ab69926d848b99c0a8f8d9b8310768292c",
          "md5": "be8dcbbc3af7928d093bd31de1479d00"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-mingwx64-2.7.4-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-mingwx64-2.7.4-SNAPSHOT-sources.jar",
          "size": 179005,
          "sha512": "cdacf06403ca262d7a3104038a3e1be89880cbd6007ab273821d3c73bcc5dc7689c377226261becfd3723be155cd057bbea8894f2f45d52ab83e7ec0369ee434",
          "sha256": "b5ac756c87fc83cbb2457ff98b25b06d069845a8b379032c8b820ca455610667",
          "sha1": "2e13acdd4fe878059d1909b136c231e3eff11328",
          "md5": "abfe41fcd332b7a2f77276b68d57d1f6"
        }
      ]
    }
  ]
}
