{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7-SNAPSHOT/snakeyaml-engine-kmp-2.7-SNAPSHOT.module",
    "group": "org.snakeyaml",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp.klib",
          "url": "snakeyaml-engine-kmp-linuxx64-2.7-SNAPSHOT.klib",
          "size": 411695,
          "sha512": "f868adbf7128696347cd9c31fd1b4d3d5e79ef5e035b232a264cd15e38e7c8189c225f321a26772518cfff1cd8d3b8f46a51788b7f4a5d0265c2ac617c61e13b",
          "sha256": "97a1c0f493c88ebe562c4b919af62b859a31f7b9755f4f69291682f540ac5dbf",
          "sha1": "9e98f17fab9ea3aff7cf5b88b130a4933df17bca",
          "md5": "0779e92b6066ee242e9c53fa705850f4"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-linuxx64-2.7-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-linuxx64-2.7-SNAPSHOT-sources.jar",
          "size": 183381,
          "sha512": "1f3f6a28f45009a8a45845952e3dbfb12db030358ee8c60d120640dffaab70f202b7e70b3d593655533f385ab75fa4d720b1ba651cffcbe972a5a9acdc4ffbfd",
          "sha256": "b3227d41472521a8b61fcc2d2d8748b93cd38b1ffd2c452b78b4a3d407f977d1",
          "sha1": "dbb5e596b650cf3d5f0f446e786e6fff15e59724",
          "md5": "6e9c691680e51c7d063944bedf4a097a"
        }
      ]
    }
  ]
}
