{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7-SNAPSHOT/snakeyaml-engine-kmp-2.7-SNAPSHOT.module",
    "group": "org.snakeyaml",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp.klib",
          "url": "snakeyaml-engine-kmp-linuxx64-2.7-SNAPSHOT.klib",
          "size": 411439,
          "sha512": "66560975199858e54cf2f4f6c03a0726c94f33e28df0ecd3a6ab1b9ca3d516c2f8b01f97f0643877e12dc0bb3822ccc62c8c5368d5830bcb247630921a6c8c8a",
          "sha256": "38aaaaf6fa557792bd8ce0c317d724708e9eb017427fc3820ccd6eff6554f8d4",
          "sha1": "a11627a67efbd67e7c6f74f703f4a2d70c63aece",
          "md5": "7e89e35e46159ad627da6df2daa972e9"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-linuxx64-2.7-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-linuxx64-2.7-SNAPSHOT-sources.jar",
          "size": 183365,
          "sha512": "12cb4943965c47c9ca002847e35615637905a737caa4d8da22faa70f733b35637359694ece29f541630dd8a9929c7fa97ba9e70f26324860e9ef45b53f944661",
          "sha256": "76de96fe37ad48be63f563b40ff356e3ec24cc4c3b6b70de1dc0db87b40cc00e",
          "sha1": "98f6d49213aa70c41996718e64baf9dc6de98b5a",
          "md5": "7e850c6bca96514fc8f654cba1653a2d"
        }
      ]
    }
  ]
}
