{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7-SNAPSHOT/snakeyaml-engine-kmp-2.7-SNAPSHOT.module",
    "group": "org.snakeyaml",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp.klib",
          "url": "snakeyaml-engine-kmp-linuxx64-2.7-SNAPSHOT.klib",
          "size": 410404,
          "sha512": "08bc1eaedfb95535eaa7839618147f820cf87513015480797ea614dc32b20590425a0d3ae6f90b9b20788277a933029c1d0bfef2fd7aca1ed980c17527f2d734",
          "sha256": "ffa5f887b4876e6aba30bdb9bb0daa059c51101fe4f8297355b025aaa7fa0c02",
          "sha1": "db22d5da571919694b0ae81803aa0e7893078e47",
          "md5": "2df8a55a0122f29df8753ebc040a139d"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-linuxx64-2.7-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-linuxx64-2.7-SNAPSHOT-sources.jar",
          "size": 183169,
          "sha512": "0b28a73cab717c97330248aaf9c3acfb43575c1cfb83f83ad3c2fcc3653e5e98a7fc7446ee83436d13331f96a6f9083608dc075ee4ecee8e27188eae25e7ebc7",
          "sha256": "d5074dca97d6bd3f00274576998969a858a031c253596a0460646e5e97ddb474",
          "sha1": "15ad4db0c2c916948ddec66d85fa46b075fc049d",
          "md5": "15493a2d0151b51cf415a8ee4c0e1551"
        }
      ]
    }
  ]
}
