{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7-SNAPSHOT/snakeyaml-engine-kmp-2.7-SNAPSHOT.module",
    "group": "org.snakeyaml",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp.klib",
          "url": "snakeyaml-engine-kmp-linuxx64-2.7-SNAPSHOT.klib",
          "size": 411818,
          "sha512": "0cc188b91cdc847a78483b74d291bb836a74721815653736b84f669d5569d1a4011347f40913d170eddee1b0afa488161a447407ad4b0a2139232bc037b8e64d",
          "sha256": "a7d0380f46cb5948d76f3799111e19370ec4fc90268872e8b3f14d8b18d6d281",
          "sha1": "f8500de6c7a1fcf474486ee5bc85d8498755a368",
          "md5": "3d2b988ecf61f983ddd5996fb9eb952e"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-linuxx64-2.7-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-linuxx64-2.7-SNAPSHOT-sources.jar",
          "size": 183892,
          "sha512": "2c7dc472179f0a409e7c5bcd698e0bbfa3d55d16ebc3a3d6342d4a8256886218e844775174acce21b14258fe4e80893c8e14374cbdce87670e2b7d4b51b07b14",
          "sha256": "57562e54c451c75cafddc2b6525d375a0c059f87b8482688bb6175f18ccd255c",
          "sha1": "81caa1277f5d5fea4949e9f701836c67230b776c",
          "md5": "41cf692d347426a27c4932e80e2b9961"
        }
      ]
    }
  ]
}
