{
  "formatVersion": "1.1",
  "component": {
    "group": "org.snakeyaml",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-metadata-2.7-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-2.7-SNAPSHOT.jar",
          "size": 53889,
          "sha512": "f33e36a64ba86b221940bead71af14de99a38b3ec041ff0a1d1b67db93f238a2f52a4e847153d131561f62c0869fd668480996bda54bc76ecd92ba1da69616fd",
          "sha256": "cd513af34beab40d8e63e8851e9aa3a1cbb7ee6b1c535e49f92c1b62189bc42b",
          "sha1": "92a572203b361cdd5bcd197cd9ec6c0042e72bac",
          "md5": "a07bebd43f73d81561a36c9ef5cdc189"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-kotlin-2.7-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-2.7-SNAPSHOT-sources.jar",
          "size": 183571,
          "sha512": "b414d986b86141dde56ed6eeca79e3b5dce6bd456e9dbea9aaecdb7bd6239959b0e78de1543222c11612d78abe1b9f0fd3521ef2ac910e76eca8b4d545aaaafa",
          "sha256": "c35815a6ef3c795e8e013052c3c6e46d4d6cdfb7085a0c760d502a85f1f804ff",
          "sha1": "02b7302f28622166a71b0b0f51dfa9ab74c3c0a7",
          "md5": "b25ff3f51dfd45bd65f80453bc3b2da2"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-js/2.7-SNAPSHOT/snakeyaml-engine-kmp-js-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-js",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-js/2.7-SNAPSHOT/snakeyaml-engine-kmp-js-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-js",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-js/2.7-SNAPSHOT/snakeyaml-engine-kmp-js-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-js",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-jvm/2.7-SNAPSHOT/snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-jvm",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-jvm/2.7-SNAPSHOT/snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-jvm",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-jvm/2.7-SNAPSHOT/snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-jvm",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-linuxx64/2.7-SNAPSHOT/snakeyaml-engine-kmp-linuxx64-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-linuxx64",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-linuxx64/2.7-SNAPSHOT/snakeyaml-engine-kmp-linuxx64-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-linuxx64",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosarm64/2.7-SNAPSHOT/snakeyaml-engine-kmp-macosarm64-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-macosarm64",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosarm64/2.7-SNAPSHOT/snakeyaml-engine-kmp-macosarm64-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-macosarm64",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosarm64/2.7-SNAPSHOT/snakeyaml-engine-kmp-macosarm64-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-macosarm64",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosx64/2.7-SNAPSHOT/snakeyaml-engine-kmp-macosx64-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-macosx64",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosx64/2.7-SNAPSHOT/snakeyaml-engine-kmp-macosx64-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-macosx64",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosx64/2.7-SNAPSHOT/snakeyaml-engine-kmp-macosx64-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-macosx64",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-mingwx64/2.7-SNAPSHOT/snakeyaml-engine-kmp-mingwx64-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-mingwx64",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-mingwx64/2.7-SNAPSHOT/snakeyaml-engine-kmp-mingwx64-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-mingwx64",
        "version": "2.7-SNAPSHOT"
      }
    }
  ]
}
