{
  "formatVersion": "1.1",
  "component": {
    "group": "org.snakeyaml",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-metadata-2.7-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-2.7-SNAPSHOT.jar",
          "size": 53935,
          "sha512": "919876ec513dba7eac41ebb2541d037aabd3d99c44e9b1f68f6d868dc84ea0d213aded5807ea6e4b69a9cb13e3c553009cea94510095b7cfece188f258f1b5eb",
          "sha256": "7cf1a0603582e1e6f0406a8b9238c0e270b1e0cd39c15b2e5e0fc04b14097ada",
          "sha1": "c7da01de22141bdb9ce9b0538a265354226a04cd",
          "md5": "f9409295ec122680a848200754b50c7f"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-kotlin-2.7-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-2.7-SNAPSHOT-sources.jar",
          "size": 183169,
          "sha512": "0b28a73cab717c97330248aaf9c3acfb43575c1cfb83f83ad3c2fcc3653e5e98a7fc7446ee83436d13331f96a6f9083608dc075ee4ecee8e27188eae25e7ebc7",
          "sha256": "d5074dca97d6bd3f00274576998969a858a031c253596a0460646e5e97ddb474",
          "sha1": "15ad4db0c2c916948ddec66d85fa46b075fc049d",
          "md5": "15493a2d0151b51cf415a8ee4c0e1551"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-js/2.7-SNAPSHOT/snakeyaml-engine-kmp-js-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-js",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-js/2.7-SNAPSHOT/snakeyaml-engine-kmp-js-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-js",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-js/2.7-SNAPSHOT/snakeyaml-engine-kmp-js-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-js",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-jvm/2.7-SNAPSHOT/snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-jvm",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-jvm/2.7-SNAPSHOT/snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-jvm",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-jvm/2.7-SNAPSHOT/snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-jvm",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-linuxx64/2.7-SNAPSHOT/snakeyaml-engine-kmp-linuxx64-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-linuxx64",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-linuxx64/2.7-SNAPSHOT/snakeyaml-engine-kmp-linuxx64-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-linuxx64",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosarm64/2.7-SNAPSHOT/snakeyaml-engine-kmp-macosarm64-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-macosarm64",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosarm64/2.7-SNAPSHOT/snakeyaml-engine-kmp-macosarm64-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-macosarm64",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosarm64/2.7-SNAPSHOT/snakeyaml-engine-kmp-macosarm64-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-macosarm64",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosx64/2.7-SNAPSHOT/snakeyaml-engine-kmp-macosx64-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-macosx64",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosx64/2.7-SNAPSHOT/snakeyaml-engine-kmp-macosx64-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-macosx64",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosx64/2.7-SNAPSHOT/snakeyaml-engine-kmp-macosx64-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-macosx64",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-mingwx64/2.7-SNAPSHOT/snakeyaml-engine-kmp-mingwx64-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-mingwx64",
        "version": "2.7-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-mingwx64/2.7-SNAPSHOT/snakeyaml-engine-kmp-mingwx64-2.7-SNAPSHOT.module",
        "group": "org.snakeyaml",
        "module": "snakeyaml-engine-kmp-mingwx64",
        "version": "2.7-SNAPSHOT"
      }
    }
  ]
}
