{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/3.0.0-SNAPSHOT/snakeyaml-engine-kmp-3.0.0-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "3.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp.klib",
          "url": "snakeyaml-engine-kmp-linuxarm64-3.0.0-SNAPSHOT.klib",
          "size": 489393,
          "sha512": "3b5c3ef8915f4e69628ad0b33df9a21a0920f396c56a4090baf2e0cfc069dcfcc1d1c205042efcfee7cdbdd59664e34157af3baace049da0229b3c839df5dc99",
          "sha256": "a0cee2abea0130e8dc3985b63b6185eefe91ad77248ed99116b2ce27452eeb00",
          "sha1": "4103aafab283df2cfab07b60a662a9b1b9433986",
          "md5": "319d5e4f6a71af3c9bc66857010d9bd7"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-linuxarm64-3.0.0-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-linuxarm64-3.0.0-SNAPSHOT-sources.jar",
          "size": 187003,
          "sha512": "d9bb85a682cd9d2926e234e351c4e851fdb74c0b86be3e5d7bee3ce9040b636c3d86c4acc5d4339c5486bf497d1ed88f6aec96cf60eddc86d3eb42bcbee8b682",
          "sha256": "a48df0cbf9def8825ec2a6bcaaa87bba87e2442cb2e65205203b476e2da4db45",
          "sha1": "17a1ce872d5bdf1138735a93841cb8bc2d8ee385",
          "md5": "f02b9824f5f03cceee71469c20e57738"
        }
      ]
    }
  ]
}
