{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7-SNAPSHOT/snakeyaml-engine-kmp-2.7-SNAPSHOT.module",
    "group": "org.snakeyaml",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp.klib",
          "url": "snakeyaml-engine-kmp-mingwx64-2.7-SNAPSHOT.klib",
          "size": 411711,
          "sha512": "fa62ae5818eb367b02a79e390aeb9daaf9cdb2314523ad7ccb41f45695e5a4166e3ef16033c6fd8844a3cf4fe59e6c6b635151ce60d12f605e3247a3463acead",
          "sha256": "ef62bd996c7c2960c09883efc2e2d6aff6c25c3482bdab09294182cd615f3efb",
          "sha1": "57c79da1e39e3f9fc0e37f4e492fa1d1b86c0e74",
          "md5": "f0d02347b888b093cab7b87ae6cd7124"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-mingwx64-2.7-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-mingwx64-2.7-SNAPSHOT-sources.jar",
          "size": 183381,
          "sha512": "1f3f6a28f45009a8a45845952e3dbfb12db030358ee8c60d120640dffaab70f202b7e70b3d593655533f385ab75fa4d720b1ba651cffcbe972a5a9acdc4ffbfd",
          "sha256": "b3227d41472521a8b61fcc2d2d8748b93cd38b1ffd2c452b78b4a3d407f977d1",
          "sha1": "dbb5e596b650cf3d5f0f446e786e6fff15e59724",
          "md5": "6e9c691680e51c7d063944bedf4a097a"
        }
      ]
    }
  ]
}
