{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7-SNAPSHOT/snakeyaml-engine-kmp-2.7-SNAPSHOT.module",
    "group": "org.snakeyaml",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp.klib",
          "url": "snakeyaml-engine-kmp-mingwx64-2.7-SNAPSHOT.klib",
          "size": 411501,
          "sha512": "b2365720604d193061432aaada34c79736577fba67cc89a10b1f95bbaaa460b53186deb86e65fdf9d276646f82a053f1a0b82fba4595916d85d7f66adebd89cb",
          "sha256": "2fc25a3f2a55da2da456b9b11fd5d62935a62de30f91415c13132ffbc86e5e84",
          "sha1": "ccfb4b75f62b087bde2dfc2fda5903566f294f58",
          "md5": "ffccc162bf87373904d51932d5753e9a"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-mingwx64-2.7-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-mingwx64-2.7-SNAPSHOT-sources.jar",
          "size": 183571,
          "sha512": "b414d986b86141dde56ed6eeca79e3b5dce6bd456e9dbea9aaecdb7bd6239959b0e78de1543222c11612d78abe1b9f0fd3521ef2ac910e76eca8b4d545aaaafa",
          "sha256": "c35815a6ef3c795e8e013052c3c6e46d4d6cdfb7085a0c760d502a85f1f804ff",
          "sha1": "02b7302f28622166a71b0b0f51dfa9ab74c3c0a7",
          "md5": "b25ff3f51dfd45bd65f80453bc3b2da2"
        }
      ]
    }
  ]
}
