{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7.2-SNAPSHOT/snakeyaml-engine-kmp-2.7.2-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.2-SNAPSHOT.klib",
          "url": "snakeyaml-engine-kmp-js-2.7.2-SNAPSHOT.klib",
          "size": 483691,
          "sha512": "1ca6dcf72f3ef640de1d9137ddce175d3531fd1c8e606b9684a6c651eff568f396caa9ed372911d663135a4f3cdb9a506ab90bd29ed9400229cc866ffe71185f",
          "sha256": "9f26a03372c0d7c15371823226e02ee995a8323f587758e1faf78759e58e4f00",
          "sha1": "6593bf9d0b3452c29721cc992b0d06be9af93d01",
          "md5": "443699e2bb845b89943eea58ad61a648"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.2-SNAPSHOT.klib",
          "url": "snakeyaml-engine-kmp-js-2.7.2-SNAPSHOT.klib",
          "size": 483691,
          "sha512": "1ca6dcf72f3ef640de1d9137ddce175d3531fd1c8e606b9684a6c651eff568f396caa9ed372911d663135a4f3cdb9a506ab90bd29ed9400229cc866ffe71185f",
          "sha256": "9f26a03372c0d7c15371823226e02ee995a8323f587758e1faf78759e58e4f00",
          "sha1": "6593bf9d0b3452c29721cc992b0d06be9af93d01",
          "md5": "443699e2bb845b89943eea58ad61a648"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.2-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-js-2.7.2-SNAPSHOT-sources.jar",
          "size": 183292,
          "sha512": "322dbd6a53ccadded7b1b11cdfcf3e54de8bc862f2523569f2e52ef4c8b8807381880d9e13cb5cfc6c3df7a97943698c8ec6a5b0d7ace91435be945f49a8cec3",
          "sha256": "4483d23722dc05b048b81e3d12a3c16b48efe345c644918c7a8a77fb131ac91a",
          "sha1": "39bd5d117a0172c5f528bf5909e72e115fd3608e",
          "md5": "4bf8b3ade9fec25272e68cd1453b4b57"
        }
      ]
    }
  ]
}
