{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7.2-SNAPSHOT/snakeyaml-engine-kmp-2.7.2-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.2-SNAPSHOT.klib",
          "url": "snakeyaml-engine-kmp-js-2.7.2-SNAPSHOT.klib",
          "size": 457492,
          "sha512": "f92b8366f38cc6e0fcab9fad794ea1c5b5d63e3d95005ad621133e5a4699775716132ab1483c7aa9ce722e9741b221409fd5406379157f4cc33fedac4e31ca09",
          "sha256": "58a9f3403e9def2503b19e01b42501b64e36771161055d8d20bacce39fbbffe6",
          "sha1": "1a4117c06ea4c972df869438f4a34bbe3c26c720",
          "md5": "96233ac3e4f0ea77969194801eb5a9d0"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.2-SNAPSHOT.klib",
          "url": "snakeyaml-engine-kmp-js-2.7.2-SNAPSHOT.klib",
          "size": 457492,
          "sha512": "f92b8366f38cc6e0fcab9fad794ea1c5b5d63e3d95005ad621133e5a4699775716132ab1483c7aa9ce722e9741b221409fd5406379157f4cc33fedac4e31ca09",
          "sha256": "58a9f3403e9def2503b19e01b42501b64e36771161055d8d20bacce39fbbffe6",
          "sha1": "1a4117c06ea4c972df869438f4a34bbe3c26c720",
          "md5": "96233ac3e4f0ea77969194801eb5a9d0"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.2-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-js-2.7.2-SNAPSHOT-sources.jar",
          "size": 183292,
          "sha512": "322dbd6a53ccadded7b1b11cdfcf3e54de8bc862f2523569f2e52ef4c8b8807381880d9e13cb5cfc6c3df7a97943698c8ec6a5b0d7ace91435be945f49a8cec3",
          "sha256": "4483d23722dc05b048b81e3d12a3c16b48efe345c644918c7a8a77fb131ac91a",
          "sha1": "39bd5d117a0172c5f528bf5909e72e115fd3608e",
          "md5": "4bf8b3ade9fec25272e68cd1453b4b57"
        }
      ]
    }
  ]
}
