{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-2.7.6-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp.klib",
          "url": "snakeyaml-engine-kmp-mingwx64-2.7.6-SNAPSHOT.klib",
          "size": 489107,
          "sha512": "ebf8dd4173759cad8c5857ba5e87043b59dced8aa653f8a375d58a5720ef894c3ac9890eeb40e78cc65fc720de24a413ac08af26c7ec6895afa79bd05532f8b3",
          "sha256": "238033bdc1956b1cab4699268c534a550a0ce914d2228dc045ed586ffbc11e3c",
          "sha1": "8b0df10c751a4bfb9b038c9c48ce7763dae33dd8",
          "md5": "28020f7b857d65e48bade0c8658c4bcf"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-mingwx64-2.7.6-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-mingwx64-2.7.6-SNAPSHOT-sources.jar",
          "size": 186958,
          "sha512": "6d5ac522918dc92fd430c87623ff8ba64ee2a713c1877fb10c7473fbcd17895df4918b57c1fd6bb98687793325eba97dd46f7cfba29ed704279e38d1e6ea23d4",
          "sha256": "e831a2ab34d85330d49d27b4db33a2da0089743b1628be695e0c5da1caf1e4b9",
          "sha1": "e51ad217b74aa90dea11990af78e544975c54fee",
          "md5": "995e265c427970310167956701b4721d"
        }
      ]
    }
  ]
}
