{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-2.7.6-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp.klib",
          "url": "snakeyaml-engine-kmp-mingwx64-2.7.6-SNAPSHOT.klib",
          "size": 434067,
          "sha512": "d0e1ce47e08bffa9124c31341cda45b9a5506247684ff4eb8fee27347f0bd563cf43525d9edfe2cfb37d4fe7312034a23a9116d6a9d0afcc28aa5df372624120",
          "sha256": "2f831d5c53d782b3623e931b9170c0b5362efb53f6fc1b855593451174056d77",
          "sha1": "a8147aaacf96d4b97829f2387b5311f57767ec94",
          "md5": "4e279ad879973831c1f47a941a647120"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-mingwx64-2.7.6-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-mingwx64-2.7.6-SNAPSHOT-sources.jar",
          "size": 186662,
          "sha512": "4e6ceece101433d09086056b8b883b8a409e10a90ca8a5db5090b06fe64b5b81a2aa4d60b816a68fda1cee230677847ceeb9037ae4641da980a6d7e886dff107",
          "sha256": "e5782b7c3bd50ba045be4eccf2d6b3fd7ea7323dd5d3d53914f709cd8a502f9b",
          "sha1": "367b3ee22d5992c78d6d98e4bc9e0a0b6ef312c2",
          "md5": "289cb792c78dc13e6ff4758d9c7acf60"
        }
      ]
    }
  ]
}
