{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-2.7.6-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp.klib",
          "url": "snakeyaml-engine-kmp-mingwx64-2.7.6-SNAPSHOT.klib",
          "size": 427169,
          "sha512": "cb523efaad1d7b5a3e491cf5acc47ba81e43970ba2284976873534f5d84b3f24a5db09989a48754840d90a7a610da81952435ac383657d000f937ce8209a6ae5",
          "sha256": "09ac06947cf3945a1cfd39525272d84481399f67885c64724b7860f4727dbaa2",
          "sha1": "8fe623b7f1fba5b8858b4fb42f6fe6ba21d78119",
          "md5": "c53806b748864cfc445e93e7a3fa06da"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-mingwx64-2.7.6-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-mingwx64-2.7.6-SNAPSHOT-sources.jar",
          "size": 184443,
          "sha512": "442eea2603d599d2661af0d0cbc9217016922a565e2e5d70ddbaeb57ccdd79abc0760f300514bbc75d0bd951635dcf1fad699d65a876021c4bb2e7287d825a4a",
          "sha256": "f24b5f234df9cb56a09304e86eca2854ebd89e2e44ff51f69662b1e7813fd374",
          "sha1": "3b5545c740be7ebbf9160faddae06c9b35359f00",
          "md5": "b8709cbefdc42e9857b7599dd0d78785"
        }
      ]
    }
  ]
}
