{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-2.7.6-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7.6-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7.6-SNAPSHOT.jar",
          "size": 439988,
          "sha512": "c9d01df9ad6568c2790be976acb249862f3c8d2aac63834243cdd5d3d1eb8d9c3034dd6084642bbc746e58dc9e0613362e7f79a02dc0c9702dad1561a5f7fb28",
          "sha256": "39cca1575c02022bb6340212a85dcc911e53e63a5ffb775b39e244a423257de3",
          "sha1": "515149be54a1fa43a79ded6fc0e2bf30247150d3",
          "md5": "bcef485545e1107e448bec0b92a805f2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7.6-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7.6-SNAPSHOT.jar",
          "size": 439988,
          "sha512": "c9d01df9ad6568c2790be976acb249862f3c8d2aac63834243cdd5d3d1eb8d9c3034dd6084642bbc746e58dc9e0613362e7f79a02dc0c9702dad1561a5f7fb28",
          "sha256": "39cca1575c02022bb6340212a85dcc911e53e63a5ffb775b39e244a423257de3",
          "sha1": "515149be54a1fa43a79ded6fc0e2bf30247150d3",
          "md5": "bcef485545e1107e448bec0b92a805f2"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7.6-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7.6-SNAPSHOT-sources.jar",
          "size": 192208,
          "sha512": "b80d754b334335661ede24a3f3ffcaf14027cc72f900da7e46d428fb23a31484d67bc1e1eb4a564428ea49b7758c90eb39423be072bb94f50fe810d4b6623cd2",
          "sha256": "613b2479516d99a16cf4b12d72eb91162e221d1cfa0a13716244cb1248d6bf00",
          "sha1": "8ba75a807b39ad0cc217d259761c1a7459a3f0ee",
          "md5": "b3552e25e77468f1cb09662ba82695cc"
        }
      ]
    }
  ]
}
