{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-2.7.6-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7.6-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7.6-SNAPSHOT.jar",
          "size": 440697,
          "sha512": "fd7ff95ec1f7d0d59f41fdf78f322e0a262092e32c14e9b186e11087cee78824f6c95440d182cf552fde5aae498695cbccd66e236b8faa803b063423c0756437",
          "sha256": "8bc52cc1f4466c460b912e15657ffcd08e0fe84df3581ec40baebc419191a62a",
          "sha1": "62053f24538840371945006cf278442840a8c881",
          "md5": "2ea841d22741de50a11dc4f8f471f428"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7.6-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7.6-SNAPSHOT.jar",
          "size": 440697,
          "sha512": "fd7ff95ec1f7d0d59f41fdf78f322e0a262092e32c14e9b186e11087cee78824f6c95440d182cf552fde5aae498695cbccd66e236b8faa803b063423c0756437",
          "sha256": "8bc52cc1f4466c460b912e15657ffcd08e0fe84df3581ec40baebc419191a62a",
          "sha1": "62053f24538840371945006cf278442840a8c881",
          "md5": "2ea841d22741de50a11dc4f8f471f428"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7.6-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7.6-SNAPSHOT-sources.jar",
          "size": 194591,
          "sha512": "ce48d01953ab24026fa611f7828c2d6a58c4200c2710f837d36f6d2231907360633fe96a70e6bf911d36155f25cb99f4ece34496eee50e8df913ccea23644c14",
          "sha256": "4acf9ae275425735bd13ace43d02259ca5445498c4235b30de7cb9b92e8a4e7f",
          "sha1": "9cb66d4b8053adc4ebe0bb3bee40050c9047a4a9",
          "md5": "d4e85af3bc2642b62b18719bef6d9246"
        }
      ]
    }
  ]
}
