{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-2.7.6-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7.6-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7.6-SNAPSHOT.jar",
          "size": 431405,
          "sha512": "d2c05387fa4884e7ac173c0225a70d54d527221c8702d223faa051ec6d566148a54a2d26b49b5f15ae8be7416cd1e27de80c08684eade83efdaa3ddecde18f0c",
          "sha256": "cda79fcc17e86ab094fbe19dcda5541b229ef2dd76770c436d38ee47d47dcd37",
          "sha1": "eb4b93fc5cb4fa289240cc2d0799b84902ea4ecc",
          "md5": "2b93098e5b5dee99abb8dc8e05ee4c61"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7.6-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7.6-SNAPSHOT.jar",
          "size": 431405,
          "sha512": "d2c05387fa4884e7ac173c0225a70d54d527221c8702d223faa051ec6d566148a54a2d26b49b5f15ae8be7416cd1e27de80c08684eade83efdaa3ddecde18f0c",
          "sha256": "cda79fcc17e86ab094fbe19dcda5541b229ef2dd76770c436d38ee47d47dcd37",
          "sha1": "eb4b93fc5cb4fa289240cc2d0799b84902ea4ecc",
          "md5": "2b93098e5b5dee99abb8dc8e05ee4c61"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7.6-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7.6-SNAPSHOT-sources.jar",
          "size": 192197,
          "sha512": "16519767e28d3a94c96ed344a2a9f986e2d203d8c11d0ab4c1eea5acf51e5847cfc0498ece7afa8b03ede482f62c5e89a94f1636110e12a23f1ce66642167133",
          "sha256": "f9e1f299844aa8d8d2f0a896413d865755b938421ad0b245697bd0a9fd0497e7",
          "sha1": "240d8f610ad732ddaffc14ce4e95a767965dd02c",
          "md5": "2b6de1257e55c74957cceede3d561bc9"
        }
      ]
    }
  ]
}
