{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-2.7.6-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7.6-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7.6-SNAPSHOT.jar",
          "size": 440649,
          "sha512": "814a8fa6bad25df0603c0b902d23669f85944fa355d332539a83d67f4eedb9850a5fb63d71e358b69b3a3dc55f83a9ea1328e62588097d28c9c16cdb738dc7a0",
          "sha256": "b3865e9315f266f8d233e2aed918fae575afba75b69e5ae184c667f85ccfa913",
          "sha1": "6f0232042fe9b9a2d2d0ccd297f051694afaa230",
          "md5": "376df0c9cff7b8752b2e580ae4d81c13"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7.6-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7.6-SNAPSHOT.jar",
          "size": 440649,
          "sha512": "814a8fa6bad25df0603c0b902d23669f85944fa355d332539a83d67f4eedb9850a5fb63d71e358b69b3a3dc55f83a9ea1328e62588097d28c9c16cdb738dc7a0",
          "sha256": "b3865e9315f266f8d233e2aed918fae575afba75b69e5ae184c667f85ccfa913",
          "sha1": "6f0232042fe9b9a2d2d0ccd297f051694afaa230",
          "md5": "376df0c9cff7b8752b2e580ae4d81c13"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7.6-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7.6-SNAPSHOT-sources.jar",
          "size": 193504,
          "sha512": "47c006ed4fe004d3ce3d00d248f60defb0faa4c648aea665e89f592d63029af5e884b0decaf922ca51a626b2716c245a34f6488b21f006d2e88bfe74ad21493b",
          "sha256": "0ef829c6c1b9a39f08140d8abc532bd181c4e81e5015e6ddb3819b34a62deb59",
          "sha1": "caca22dc3cce6bac03efc7e65dc6882a8892870b",
          "md5": "586789751129c49d3ec269923d391009"
        }
      ]
    }
  ]
}
