{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7-SNAPSHOT/snakeyaml-engine-kmp-2.7-SNAPSHOT.module",
    "group": "org.snakeyaml",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT.jar",
          "size": 427150,
          "sha512": "cfdf924cbe4b50a6ad44483c11a2884f224676a37711ebfc8c5183c66aa33e398c8acc67994b83cf572f7acbce05e4accc24a2a44030c76bd3a0745ca9bb6ea6",
          "sha256": "04f20ea2237a66938fbc6fa2b8b127b16ee51cc21aa81e19f33758a925794a98",
          "sha1": "d1c9e08d94cdefe74129e7f24320dbe61e923595",
          "md5": "0f3d63368074f0f6ea11356c1beee9d2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT.jar",
          "size": 427150,
          "sha512": "cfdf924cbe4b50a6ad44483c11a2884f224676a37711ebfc8c5183c66aa33e398c8acc67994b83cf572f7acbce05e4accc24a2a44030c76bd3a0745ca9bb6ea6",
          "sha256": "04f20ea2237a66938fbc6fa2b8b127b16ee51cc21aa81e19f33758a925794a98",
          "sha1": "d1c9e08d94cdefe74129e7f24320dbe61e923595",
          "md5": "0f3d63368074f0f6ea11356c1beee9d2"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT-sources.jar",
          "size": 191506,
          "sha512": "5a98b2dec75ad082c5cfa280d83b4b694d80cc74cb558439cd292530f3b343f04d25ea4146b999304c885d5665e1430a1cd0018efa7d53fb53cf28100906aa32",
          "sha256": "5292cbbba994c12a554f75186ad768d35625ede5a8b29ad6f209b13c6306d4ed",
          "sha1": "56d659d5061cd5c0ec7daad6daa5c51641ffaec2",
          "md5": "426685b3ba62e8a1c7ae413cfd3d1adb"
        }
      ]
    }
  ]
}
