{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7-SNAPSHOT/snakeyaml-engine-kmp-2.7-SNAPSHOT.module",
    "group": "org.snakeyaml",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT.jar",
          "size": 426241,
          "sha512": "6b933fb60103b2e5d8b7fb2a2253f1b057d9da2e956b5e1d06e3f345cde55c0ff550efb909b125b1b0470ba375ba9f94d831adb40146d9363c7c28dd109d47b3",
          "sha256": "042c71dc356b716b27d724a18bbdaddab520578ae5fa82255918bb1b7f75e141",
          "sha1": "628d2f51f98766b2189a38bf49cf509fd37a0fd9",
          "md5": "1795dd160a7c2f8e06fb7f1ee3f6ed72"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT.jar",
          "size": 426241,
          "sha512": "6b933fb60103b2e5d8b7fb2a2253f1b057d9da2e956b5e1d06e3f345cde55c0ff550efb909b125b1b0470ba375ba9f94d831adb40146d9363c7c28dd109d47b3",
          "sha256": "042c71dc356b716b27d724a18bbdaddab520578ae5fa82255918bb1b7f75e141",
          "sha1": "628d2f51f98766b2189a38bf49cf509fd37a0fd9",
          "md5": "1795dd160a7c2f8e06fb7f1ee3f6ed72"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT-sources.jar",
          "size": 191320,
          "sha512": "0480b33f097405c28a369f8a22d4660c2cb1e6f58f9bf31a8b1ca333ac2be1ad454eb69a6e1fa8fdc983f362880438cb461ea11e546392f9c2b72d055da9d0b0",
          "sha256": "6f564a0569c1e44a12949b07672eb506ac7e18489ef1ac9203f9f187d1c8714f",
          "sha1": "b5636504450cc17f3cc56238e13abecffbeb98ab",
          "md5": "c497ce46b10db2ac6d8efb45576ea4c7"
        }
      ]
    }
  ]
}
