{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7-SNAPSHOT/snakeyaml-engine-kmp-2.7-SNAPSHOT.module",
    "group": "org.snakeyaml",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT.jar",
          "size": 427146,
          "sha512": "d7d1e28510766767de81a1671c483aeaecc77aae440d8a42bd12abdffbce00053780ea0798b0170606c288d00231a2d0ecf94d81eae062626b413291ab96d339",
          "sha256": "090ba60b9dd16ce57f269b01fbe8c42f0cadedbc1f59f449ebf3c82de58f0c3d",
          "sha1": "1144daba7920457de00361cfb79fd4085dc87f34",
          "md5": "4315856fff29ee169a892f7769308290"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT.jar",
          "size": 427146,
          "sha512": "d7d1e28510766767de81a1671c483aeaecc77aae440d8a42bd12abdffbce00053780ea0798b0170606c288d00231a2d0ecf94d81eae062626b413291ab96d339",
          "sha256": "090ba60b9dd16ce57f269b01fbe8c42f0cadedbc1f59f449ebf3c82de58f0c3d",
          "sha1": "1144daba7920457de00361cfb79fd4085dc87f34",
          "md5": "4315856fff29ee169a892f7769308290"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT-sources.jar",
          "size": 190965,
          "sha512": "a382641d7bc9163f451a69fc813375d415f23a76f0d053db0b3581c9315edac82cd767130757ab0157b45561157716a454b3fbe1be5392b8abd41ddff03fc207",
          "sha256": "bfd5a8c92ec71269a5af609b7c31c209f34227ddd029f514fec2175cdc658242",
          "sha1": "b8bd2effae34b1ac058a8789670b628d9034518b",
          "md5": "59b450f6d51c722270e85326be932bcd"
        }
      ]
    }
  ]
}
