{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7-SNAPSHOT/snakeyaml-engine-kmp-2.7-SNAPSHOT.module",
    "group": "org.snakeyaml",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT.jar",
          "size": 426253,
          "sha512": "a3b0d65f749d9d2d45bea20dbf7093ae9178e4eb1591fb6182f5a017689a0a7d6f83a198486c0ec8ea15fe8b63f86aa0465811314fe1942d67f9d56c070d4c5d",
          "sha256": "302cf70ef69616d7f34ce1e5a25b23d8b2b15f33d9b870e10d4e8d3f0becc93d",
          "sha1": "d43f2edece4660406b82207645fd1138c918b5e3",
          "md5": "3c040e265ad7b178d3c3b05dfc7978d5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT.jar",
          "size": 426253,
          "sha512": "a3b0d65f749d9d2d45bea20dbf7093ae9178e4eb1591fb6182f5a017689a0a7d6f83a198486c0ec8ea15fe8b63f86aa0465811314fe1942d67f9d56c070d4c5d",
          "sha256": "302cf70ef69616d7f34ce1e5a25b23d8b2b15f33d9b870e10d4e8d3f0becc93d",
          "sha1": "d43f2edece4660406b82207645fd1138c918b5e3",
          "md5": "3c040e265ad7b178d3c3b05dfc7978d5"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7-SNAPSHOT-sources.jar",
          "size": 190760,
          "sha512": "83f860c3866ee473dcd3ce8cf1fdb7119ddd25a9496628059481e0e248541931417730fb1956195a2ccd13cd8877a230d2cf47aa864505e698a7a07eb0c88e08",
          "sha256": "70ef07e26b489c71ee8a055e720ac146d550b4881a9e3cfc3e8f2867cbc1548c",
          "sha1": "2507b342e256954a3ce28740d805063924d83fa5",
          "md5": "56fe680061c9a6cec76d8036f2ff1b04"
        }
      ]
    }
  ]
}
