{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7-SNAPSHOT/snakeyaml-engine-kmp-2.7-SNAPSHOT.module",
    "group": "org.snakeyaml",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7-SNAPSHOT.klib",
          "url": "snakeyaml-engine-kmp-js-2.7-SNAPSHOT.klib",
          "size": 457192,
          "sha512": "2d2d6d2a4cc4f744be9a9365bcd176e7bd82c8c77970246e25e49dbe8199e21c6eaf263654b28b1950461c1725582a1a868bc64ad02c2877b1da0d7baffe2e2b",
          "sha256": "e1006fd690e24ab933f22db7de49b49c118954af71533846ea1c061a3e556afd",
          "sha1": "6b79fe7028d7d7fe6bd26b982794c34bfab22a1d",
          "md5": "023d428d30da0d0186e59d49dd8ca2e3"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7-SNAPSHOT.klib",
          "url": "snakeyaml-engine-kmp-js-2.7-SNAPSHOT.klib",
          "size": 457192,
          "sha512": "2d2d6d2a4cc4f744be9a9365bcd176e7bd82c8c77970246e25e49dbe8199e21c6eaf263654b28b1950461c1725582a1a868bc64ad02c2877b1da0d7baffe2e2b",
          "sha256": "e1006fd690e24ab933f22db7de49b49c118954af71533846ea1c061a3e556afd",
          "sha1": "6b79fe7028d7d7fe6bd26b982794c34bfab22a1d",
          "md5": "023d428d30da0d0186e59d49dd8ca2e3"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-js-2.7-SNAPSHOT-sources.jar",
          "size": 183305,
          "sha512": "087813aafa38f0fe2b61c40c3447e92d2c2d08d294fcf1d1a1c99ef83def5ab79e2ef8f384971bc04f80d65ca8629949db30583ff9f4aa79ba79ead4acc8b5df",
          "sha256": "4d550e414333dbb6fe80650e36f4b1e643fd12b13c898e0d81f5cfe5ba56341e",
          "sha1": "198a4a56aa86b9c4d35c8f4c2078c50e05ae5273",
          "md5": "8cdcd3d4f52affc44b879ab86d3fa2af"
        }
      ]
    }
  ]
}
