{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7-SNAPSHOT/snakeyaml-engine-kmp-2.7-SNAPSHOT.module",
    "group": "org.snakeyaml",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7-SNAPSHOT.klib",
          "url": "snakeyaml-engine-kmp-js-2.7-SNAPSHOT.klib",
          "size": 458459,
          "sha512": "1a69d3f1690bc6f506532309a58cd3e365e4ebd7b2b2cbc58268fa7796c3c6efb6baca0d42ae6d8aeb8d48dee19f6f31fba0a3b39fa64f85237b691d6b050ee0",
          "sha256": "e768cd9595e874214ac21f22d2f428d168c73b6419ac5aae07e31975c6135b8b",
          "sha1": "eea7ecb7c834febbf4c88029dbd770daae5206e4",
          "md5": "5c1ebe07be46dcedf1430c96892699c9"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7-SNAPSHOT.klib",
          "url": "snakeyaml-engine-kmp-js-2.7-SNAPSHOT.klib",
          "size": 458459,
          "sha512": "1a69d3f1690bc6f506532309a58cd3e365e4ebd7b2b2cbc58268fa7796c3c6efb6baca0d42ae6d8aeb8d48dee19f6f31fba0a3b39fa64f85237b691d6b050ee0",
          "sha256": "e768cd9595e874214ac21f22d2f428d168c73b6419ac5aae07e31975c6135b8b",
          "sha1": "eea7ecb7c834febbf4c88029dbd770daae5206e4",
          "md5": "5c1ebe07be46dcedf1430c96892699c9"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-js-2.7-SNAPSHOT-sources.jar",
          "size": 183517,
          "sha512": "c781d30093e4db53be555f47e222802aabcb42122cc3c5a56de85cad1203aa5d26ec4375b8e1dc95f8b6878652f126507ae231aa324aab74c3c7604cd2e6a550",
          "sha256": "c963592029446f0ce4dce4480dd8a60d8d0a42418dc8a2d343c386ad7cbb7256",
          "sha1": "e331667026e32c18a26b04769832d65715095968",
          "md5": "081ce7f8d8425bfcd8e945c21a52e210"
        }
      ]
    }
  ]
}
