{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7.1-SNAPSHOT/snakeyaml-engine-kmp-2.7.1-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp.klib",
          "url": "snakeyaml-engine-kmp-macosarm64-2.7.1-SNAPSHOT.klib",
          "size": 410922,
          "sha512": "0478b9829c9d43b238b7e085b7c185bfd3790608ccb7380e5ffd039ec5618a46c54bad4036be1e80be4c83b21c69be382a00c392312b656e98163d92f73a49d1",
          "sha256": "666e656694ccbe98f4071b42711b8287e7f3cb68a639cd2545cd40399a605732",
          "sha1": "631fe4ac96cc232b343532952001759e23e85563",
          "md5": "7a337b754892a569308bdd51279e7704"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-macosarm64-2.7.1-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-macosarm64-2.7.1-SNAPSHOT-sources.jar",
          "size": 183245,
          "sha512": "dedeed5bb7a27bc373af57e7d2b1a2df9beb7e4dd1028dc10dc7df059ec219cb5c400aae8e8369ec53fcc94e4d74ab4d39fb192aa6e751fc22c8ccf2a613844f",
          "sha256": "e6ae1801ce3e6cc876770759cfd42cff50c9f997707e5f968b39a9931acf6c8a",
          "sha1": "954964251969e444aa6e7df6acebd6cff5f62eff",
          "md5": "a69f896bd16c240eb63ca677a10e982c"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-macosarm64-2.7.1-SNAPSHOT-metadata.jar",
          "url": "snakeyaml-engine-kmp-macosarm64-2.7.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
