{
  "formatVersion": "1.1",
  "component": {
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-metadata-2.7.6-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-2.7.6-SNAPSHOT.jar",
          "size": 52968,
          "sha512": "906cf26d97048a9eb018326bf95d03f6c13725fa6bec2aa8dccc515791cc1abb995d17ec1fdf3a4f21e120143ae1bf034352e43f136b94aa1133a0fb37778899",
          "sha256": "1a2d4408990c2e0476a51d4223faabe529e4f680416302cb53f30ff3790d1d22",
          "sha1": "e8825dd9a7ef1ba2a34a759415925c0bf071c465",
          "md5": "6110d0b39968dac8c6d4864969fcd970"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-kotlin-2.7.6-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-2.7.6-SNAPSHOT-sources.jar",
          "size": 184443,
          "sha512": "2b50e7e2162648c7c90c43398b73924aae93775f46282b8602e0fa8ea4921c08069d2c00eebd5edb2321064c932dd18e0f43229fecdf822955661af9cba8732a",
          "sha256": "eeccc085db60c873649545a0c627689a115a279d415313fb1436e06af02c566f",
          "sha1": "a66b9cdf39479e85b085d12d642f113bf1eb86c7",
          "md5": "5cba311cc0067db8a594d1838ed42eab"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iosarm64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-iosarm64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iosarm64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iosarm64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-iosarm64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iosarm64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iosarm64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-iosarm64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iosarm64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iossimulatorarm64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-iossimulatorarm64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iossimulatorarm64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iossimulatorarm64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-iossimulatorarm64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iossimulatorarm64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iossimulatorarm64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-iossimulatorarm64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iossimulatorarm64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iosx64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-iosx64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iosx64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iosx64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-iosx64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iosx64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iosx64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-iosx64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iosx64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-js/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-js",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-js/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-js",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-js/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-js",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-jvm/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-jvm-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-jvm",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-jvm/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-jvm-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-jvm",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-jvm/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-jvm-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-jvm",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-linuxarm64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-linuxarm64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-linuxarm64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-linuxarm64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-linuxarm64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-linuxarm64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-linuxx64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-linuxx64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-linuxx64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-linuxx64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-linuxx64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-linuxx64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosarm64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-macosarm64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosarm64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosarm64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-macosarm64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosarm64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosarm64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-macosarm64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosarm64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosx64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-macosx64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosx64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosx64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-macosx64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosx64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosx64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-macosx64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosx64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-mingwx64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-mingwx64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-mingwx64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-mingwx64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-mingwx64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-mingwx64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvosarm64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-tvosarm64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvosarm64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvosarm64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-tvosarm64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvosarm64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvosarm64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-tvosarm64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvosarm64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvossimulatorarm64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-tvossimulatorarm64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvossimulatorarm64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvossimulatorarm64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-tvossimulatorarm64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvossimulatorarm64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvossimulatorarm64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-tvossimulatorarm64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvossimulatorarm64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvosx64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-tvosx64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvosx64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvosx64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-tvosx64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvosx64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvosx64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-tvosx64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvosx64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosarm32/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-watchosarm32-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosarm32",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosarm32/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-watchosarm32-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosarm32",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosarm32/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-watchosarm32-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosarm32",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosarm64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-watchosarm64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosarm64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosarm64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-watchosarm64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosarm64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosarm64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-watchosarm64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosarm64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchossimulatorarm64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-watchossimulatorarm64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchossimulatorarm64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchossimulatorarm64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-watchossimulatorarm64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchossimulatorarm64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchossimulatorarm64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-watchossimulatorarm64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchossimulatorarm64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosx64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-watchosx64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosx64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosx64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-watchosx64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosx64",
        "version": "2.7.6-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosx64/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-watchosx64-2.7.6-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosx64",
        "version": "2.7.6-SNAPSHOT"
      }
    }
  ]
}
