{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7.2-SNAPSHOT/snakeyaml-engine-kmp-2.7.2-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp.klib",
          "url": "snakeyaml-engine-kmp-linuxx64-2.7.2-SNAPSHOT.klib",
          "size": 424606,
          "sha512": "9dab71e8740edc0a6ec9981165e23084cf1313d91eeb6ebe56bda295d0c3bd33a1496d45028367e03fe41ce8da06136e85f686f24a70c4bad40c54b63334d4b1",
          "sha256": "73d6a51018f0d7069b538ba417dbdb120232a08a725136f791caa6dff0e14cb4",
          "sha1": "da336955fdf6a57250b2315eced41743a9edf503",
          "md5": "6b67dd94caea6e5fa5c14c860f37f2b7"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-linuxx64-2.7.2-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-linuxx64-2.7.2-SNAPSHOT-sources.jar",
          "size": 179005,
          "sha512": "cdacf06403ca262d7a3104038a3e1be89880cbd6007ab273821d3c73bcc5dc7689c377226261becfd3723be155cd057bbea8894f2f45d52ab83e7ec0369ee434",
          "sha256": "b5ac756c87fc83cbb2457ff98b25b06d069845a8b379032c8b820ca455610667",
          "sha1": "2e13acdd4fe878059d1909b136c231e3eff11328",
          "md5": "abfe41fcd332b7a2f77276b68d57d1f6"
        }
      ]
    }
  ]
}
