{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/3.0.2-SNAPSHOT/snakeyaml-engine-kmp-3.0.2-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "3.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-3.0.2-SNAPSHOT.klib",
          "url": "snakeyaml-engine-kmp-js-3.0.2-SNAPSHOT.klib",
          "size": 491614,
          "sha512": "4916e77543f73d16d54018fe4d450b7616368d7841830e2ab5b867421bb7d125b23810d612de905af7ae4a024ef4eed962ba5895c90ac2449b7f626d449c4bfd",
          "sha256": "23f0368b62bfa84ef97427ded66a24531a7d5be9ae7c77c401379bfc79ea769f",
          "sha1": "ccb4bd671b748ecde021e6cb0fb68975a6e36136",
          "md5": "fddf196baef81c95d699147a707bf1e9"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-3.0.2-SNAPSHOT.klib",
          "url": "snakeyaml-engine-kmp-js-3.0.2-SNAPSHOT.klib",
          "size": 491614,
          "sha512": "4916e77543f73d16d54018fe4d450b7616368d7841830e2ab5b867421bb7d125b23810d612de905af7ae4a024ef4eed962ba5895c90ac2449b7f626d449c4bfd",
          "sha256": "23f0368b62bfa84ef97427ded66a24531a7d5be9ae7c77c401379bfc79ea769f",
          "sha1": "ccb4bd671b748ecde021e6cb0fb68975a6e36136",
          "md5": "fddf196baef81c95d699147a707bf1e9"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-3.0.2-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-js-3.0.2-SNAPSHOT-sources.jar",
          "size": 191200,
          "sha512": "48fd4170d54ffeb1cb1ca0c915190785f4bf5c13013bf4ba2169741d1017285356c7844ba2f1983a315f314537bd34a9e200b30c3a2f598732dd6c8e9f0aa161",
          "sha256": "6f0699b5195f3b2fb299ea6695df2ea8bb0d933e2bf7bd1ca3ed1dd7eef8e461",
          "sha1": "8cc1953d9d32a064b2aabfe399a85e86a07b8e97",
          "md5": "2a17452402163865b12825142b5926c2"
        }
      ]
    }
  ]
}
