{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7.1/snakeyaml-engine-kmp-2.7.1.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.1.klib",
          "url": "snakeyaml-engine-kmp-js-2.7.1.klib",
          "size": 457191,
          "sha512": "b94a5e5eeeb599fd1ef77aa1e1f67b8377951f41c331f4ba219fd9f6c7a89453ba08b6f4f4727717990b91791451bb09f6ce5cb56cfd57b25b9fb8d151672d95",
          "sha256": "0c582fb87bdfea4eb03224a1b3bf65b97e46c162986e7d18c5661d427fd15449",
          "sha1": "8784c38cc971839850449b74dddbcf5de060dd78",
          "md5": "beb72d15696c0e4c8626a440a7a4dfa6"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.1.klib",
          "url": "snakeyaml-engine-kmp-js-2.7.1.klib",
          "size": 457191,
          "sha512": "b94a5e5eeeb599fd1ef77aa1e1f67b8377951f41c331f4ba219fd9f6c7a89453ba08b6f4f4727717990b91791451bb09f6ce5cb56cfd57b25b9fb8d151672d95",
          "sha256": "0c582fb87bdfea4eb03224a1b3bf65b97e46c162986e7d18c5661d427fd15449",
          "sha1": "8784c38cc971839850449b74dddbcf5de060dd78",
          "md5": "beb72d15696c0e4c8626a440a7a4dfa6"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.1-sources.jar",
          "url": "snakeyaml-engine-kmp-js-2.7.1-sources.jar",
          "size": 183292,
          "sha512": "322dbd6a53ccadded7b1b11cdfcf3e54de8bc862f2523569f2e52ef4c8b8807381880d9e13cb5cfc6c3df7a97943698c8ec6a5b0d7ace91435be945f49a8cec3",
          "sha256": "4483d23722dc05b048b81e3d12a3c16b48efe345c644918c7a8a77fb131ac91a",
          "sha1": "39bd5d117a0172c5f528bf5909e72e115fd3608e",
          "md5": "4bf8b3ade9fec25272e68cd1453b4b57"
        }
      ]
    }
  ]
}
