{
  "formatVersion": "1.1",
  "component": {
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-metadata-2.7.5-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-2.7.5-SNAPSHOT.jar",
          "size": 49923,
          "sha512": "26cb979f04477a1c4e096caea5c953e1b24be7debf14e65bc3c76a8dbaafe7c79469b708b5b174b75f7f9b986b3ecd503a803c814ae98b1d9f970361dd4061b6",
          "sha256": "e61fab53fe52a26b5dde86dcb131ddc4b300781131e885f936441f4f45d23009",
          "sha1": "769560a15cfe51df97ea185dcda4a0ceac44f5ba",
          "md5": "1a583440a8f3082dd069ac71fe69e530"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-kotlin-2.7.5-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-2.7.5-SNAPSHOT-sources.jar",
          "size": 178994,
          "sha512": "85065fd7e7581ddceb7108f09e6a524045a4cd66d60790916d4793f1f186f6c5307f8f40c879b87ff5cc7fcf51fde4b986d47a5f7e24f20680056f253b917140",
          "sha256": "7936af0454c34d2b85e769512677826ecd1f657e74dd94455077fcf702d2f2e3",
          "sha1": "b89954422885931ecd77f6095c965c2d0a7bd1af",
          "md5": "2010ce6d4d9c2f134a53efbe0a56d29e"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iosarm64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-iosarm64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iosarm64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iosarm64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-iosarm64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iosarm64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iosarm64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-iosarm64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iosarm64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iossimulatorarm64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-iossimulatorarm64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iossimulatorarm64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iossimulatorarm64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-iossimulatorarm64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iossimulatorarm64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iossimulatorarm64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-iossimulatorarm64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iossimulatorarm64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iosx64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-iosx64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iosx64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iosx64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-iosx64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iosx64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-iosx64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-iosx64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-iosx64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-js/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-js-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-js",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-js/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-js-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-js",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-js/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-js-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-js",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-jvm/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-jvm-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-jvm",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-jvm/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-jvm-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-jvm",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-jvm/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-jvm-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-jvm",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-linuxarm64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-linuxarm64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-linuxarm64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-linuxarm64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-linuxarm64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-linuxarm64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-linuxx64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-linuxx64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-linuxx64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-linuxx64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-linuxx64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-linuxx64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosarm64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-macosarm64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosarm64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosarm64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-macosarm64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosarm64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosarm64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-macosarm64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosarm64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosx64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-macosx64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosx64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosx64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-macosx64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosx64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosx64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-macosx64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosx64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-mingwx64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-mingwx64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-mingwx64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-mingwx64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-mingwx64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-mingwx64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvosarm64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-tvosarm64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvosarm64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvosarm64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-tvosarm64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvosarm64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvosarm64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-tvosarm64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvosarm64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvossimulatorarm64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-tvossimulatorarm64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvossimulatorarm64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvossimulatorarm64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-tvossimulatorarm64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvossimulatorarm64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvossimulatorarm64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-tvossimulatorarm64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvossimulatorarm64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvosx64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-tvosx64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvosx64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvosx64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-tvosx64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvosx64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-tvosx64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-tvosx64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-tvosx64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosarm32/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-watchosarm32-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosarm32",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosarm32/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-watchosarm32-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosarm32",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosarm32/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-watchosarm32-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosarm32",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosarm64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-watchosarm64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosarm64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosarm64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-watchosarm64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosarm64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosarm64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-watchosarm64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosarm64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchossimulatorarm64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-watchossimulatorarm64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchossimulatorarm64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchossimulatorarm64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-watchossimulatorarm64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchossimulatorarm64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchossimulatorarm64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-watchossimulatorarm64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchossimulatorarm64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosx64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-watchosx64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosx64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosx64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-watchosx64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosx64",
        "version": "2.7.5-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-watchosx64/2.7.5-SNAPSHOT/snakeyaml-engine-kmp-watchosx64-2.7.5-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-watchosx64",
        "version": "2.7.5-SNAPSHOT"
      }
    }
  ]
}
