{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/3.0.2-SNAPSHOT/snakeyaml-engine-kmp-3.0.2-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "3.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp.klib",
          "url": "snakeyaml-engine-kmp-linuxx64-3.0.2-SNAPSHOT.klib",
          "size": 489568,
          "sha512": "b2b73d5857843b99e93be3c71bdfb4cfe6e2eb7dc98e24b66c1ef11d6d9f2c84224a78d4a72cc1ecb54014748b453c85d5ecc0aa39050c75210a7f4017eeff45",
          "sha256": "9f0d705aea59fdda56521326e0f6920cda4bc388c60f7d48567963b635a0001a",
          "sha1": "fff51637bd89045b8701b340e85eecf7cdf562e4",
          "md5": "c8db62fd4fab3a0e52e95c8f811fdbdc"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-linuxx64-3.0.2-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-linuxx64-3.0.2-SNAPSHOT-sources.jar",
          "size": 187036,
          "sha512": "d35a80c0532e4d1d8b412180b6fa475f9c938397ed578cffe0177f12d44894ee9ee56ceee3eabe9d7c2704292e340a20a88e271a78e0f0ab4d9e7dc66800bded",
          "sha256": "870377d9737991b086a7fa2a32b8b3c1e2536b32b41cab19d59d0dc5142edf1b",
          "sha1": "9282880c68b3ea513ba0c2e64448b79294eb07af",
          "md5": "c96f0e77b559a08450899c640bbad603"
        }
      ]
    }
  ]
}
