{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/3.0.0-SNAPSHOT/snakeyaml-engine-kmp-3.0.0-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "3.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-3.0.0-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-3.0.0-SNAPSHOT.jar",
          "size": 438318,
          "sha512": "6c586a6226356a0d46718d53fb423f5dcf132998da9191b3dc10233bc6838c07ab6a0800a8cb80c56d9193e9c8d0cbc610f0a31c0188bf78d79737536f296f78",
          "sha256": "062c920a8da06c06115cf830c081d26bd6c376b0dbd766ff152544fccc348bf9",
          "sha1": "20a7f57f6aba9e36d8d18f71fa1ad5d7bfd8606e",
          "md5": "6dc82815952498908eed896cee51ecdd"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-3.0.0-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-3.0.0-SNAPSHOT.jar",
          "size": 438318,
          "sha512": "6c586a6226356a0d46718d53fb423f5dcf132998da9191b3dc10233bc6838c07ab6a0800a8cb80c56d9193e9c8d0cbc610f0a31c0188bf78d79737536f296f78",
          "sha256": "062c920a8da06c06115cf830c081d26bd6c376b0dbd766ff152544fccc348bf9",
          "sha1": "20a7f57f6aba9e36d8d18f71fa1ad5d7bfd8606e",
          "md5": "6dc82815952498908eed896cee51ecdd"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-3.0.0-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-jvm-3.0.0-SNAPSHOT-sources.jar",
          "size": 194964,
          "sha512": "182ada0f55f2af84543eaf9abaa05bd47354dd5f029cbb001b36aa26f52279b7ab6f1477ff27d1ea31e0dfa9b20b058f90f44399c658dca4029175862a719da6",
          "sha256": "483673edaeb10eb8f0d641f974a94470bef662b936d3ceef035e3e4a0c73045c",
          "sha1": "2676b619a0c609bb140e856a5edf14892694ff77",
          "md5": "03ce631a16ccb9cc1f591f2ce77b1e44"
        }
      ]
    }
  ]
}
