{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7.2-SNAPSHOT/snakeyaml-engine-kmp-2.7.2-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7.2-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7.2-SNAPSHOT.jar",
          "size": 428701,
          "sha512": "05e38745d7e0387620b2b7e9e4b1c85a7c9e56a64b38d6d915bd98af7d127c37c147bbacfc47389ece2bcfa47ed86f693c38d4c9d3da73bf7c9e474f3f92d068",
          "sha256": "98111985c2bac5acb6805785d3d6f6e952d3e42999ed86a72fd4e6608bad1114",
          "sha1": "d0164ad2d1943a3ee9d7da739eeae13d4e429f32",
          "md5": "4dba045da81cd19f75fa5fad5750bb4c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7.2-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7.2-SNAPSHOT.jar",
          "size": 428701,
          "sha512": "05e38745d7e0387620b2b7e9e4b1c85a7c9e56a64b38d6d915bd98af7d127c37c147bbacfc47389ece2bcfa47ed86f693c38d4c9d3da73bf7c9e474f3f92d068",
          "sha256": "98111985c2bac5acb6805785d3d6f6e952d3e42999ed86a72fd4e6608bad1114",
          "sha1": "d0164ad2d1943a3ee9d7da739eeae13d4e429f32",
          "md5": "4dba045da81cd19f75fa5fad5750bb4c"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7.2-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7.2-SNAPSHOT-sources.jar",
          "size": 190749,
          "sha512": "2fe40c8aa0dae105825c92a7581b77e1767c68a1c362ee08cddc843824e3580f4695e9e2737c24bbe63ea272b69de22a97c6237bd208cd61342a9ab3ff257f80",
          "sha256": "3364c1b07adb61db2389cc8c3359e8b3dcbc1793e3dd35e8ccf5b24daf7fbb74",
          "sha1": "ef1cc0fd4faecd061011e4552d2cd4ef557abc27",
          "md5": "1cce7b7c8e193fa1b0f08efeb29f7e0f"
        }
      ]
    }
  ]
}
