{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7.2-SNAPSHOT/snakeyaml-engine-kmp-2.7.2-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7.2-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7.2-SNAPSHOT.jar",
          "size": 428316,
          "sha512": "b9dbbaf7098677f4a42f85c3b6a57b4e1df67036c8533e04ef1de8473346e0ec69856607664c9a1efe7669f708f69fe3b35c670c5633e0634a77eb66c72953c0",
          "sha256": "fa4a830d59082151c00c6db6c84e94caa94a4b0aad9a50d5c7bfb9b46216fd40",
          "sha1": "7592927a911461d2a54a390e4cca9b79157b2342",
          "md5": "cb22f8d389e48d4c7f0360101668a6d2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7.2-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7.2-SNAPSHOT.jar",
          "size": 428316,
          "sha512": "b9dbbaf7098677f4a42f85c3b6a57b4e1df67036c8533e04ef1de8473346e0ec69856607664c9a1efe7669f708f69fe3b35c670c5633e0634a77eb66c72953c0",
          "sha256": "fa4a830d59082151c00c6db6c84e94caa94a4b0aad9a50d5c7bfb9b46216fd40",
          "sha1": "7592927a911461d2a54a390e4cca9b79157b2342",
          "md5": "cb22f8d389e48d4c7f0360101668a6d2"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7.2-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7.2-SNAPSHOT-sources.jar",
          "size": 190749,
          "sha512": "2fe40c8aa0dae105825c92a7581b77e1767c68a1c362ee08cddc843824e3580f4695e9e2737c24bbe63ea272b69de22a97c6237bd208cd61342a9ab3ff257f80",
          "sha256": "3364c1b07adb61db2389cc8c3359e8b3dcbc1793e3dd35e8ccf5b24daf7fbb74",
          "sha1": "ef1cc0fd4faecd061011e4552d2cd4ef557abc27",
          "md5": "1cce7b7c8e193fa1b0f08efeb29f7e0f"
        }
      ]
    }
  ]
}
