{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7.2-SNAPSHOT/snakeyaml-engine-kmp-2.7.2-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7.2-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7.2-SNAPSHOT.jar",
          "size": 421165,
          "sha512": "67e20bffd33ef5c632bf0d926082c749fbb7dbc2932ce95deef55bc028275d2de433729523eb7a5b077f2093d32c9709396467e97cd62d13a131b4ccef91703f",
          "sha256": "85615778a007d6d80612fe66525af80874ab617bf12182a95655a015036217b6",
          "sha1": "843b469d1e1a49abe0ef3fa6281d3361ae0654c7",
          "md5": "8cdc4a0cbae723e4a1d72a7a9c27d756"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7.2-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7.2-SNAPSHOT.jar",
          "size": 421165,
          "sha512": "67e20bffd33ef5c632bf0d926082c749fbb7dbc2932ce95deef55bc028275d2de433729523eb7a5b077f2093d32c9709396467e97cd62d13a131b4ccef91703f",
          "sha256": "85615778a007d6d80612fe66525af80874ab617bf12182a95655a015036217b6",
          "sha1": "843b469d1e1a49abe0ef3fa6281d3361ae0654c7",
          "md5": "8cdc4a0cbae723e4a1d72a7a9c27d756"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-jvm-2.7.2-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-jvm-2.7.2-SNAPSHOT-sources.jar",
          "size": 186640,
          "sha512": "b4bd30276ff830bc3165d88d8802e22b4db2329b699d53d39bb910e5701184bb36fccc2ca77000a5ed450b47da51264dd0987d97fd6e4fab9e2631b45c5e428b",
          "sha256": "d13aab5bce8859e16f997836f2516bba02557609ad470cec6259bc2057538e6a",
          "sha1": "236480d720700bbd792d353307f5e9cb386f536f",
          "md5": "03707809e884de1f595a8b63d374aa08"
        }
      ]
    }
  ]
}
