{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-2.7.6-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.klib",
          "url": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.klib",
          "size": 479614,
          "sha512": "59a1255d4481c2a665efd84d3790d9f197f615309aeeb82214a99c204ebb18f0fede0f7f7de1eba342e90a7a54355a5e5f91ea191c53e3ffb346acc461cc2974",
          "sha256": "c5bc531d22fef8eb6838a151ad571b617d283fdef6079d2812c8d17c2b3d96d2",
          "sha1": "9e30a81cf89a9533bfb4d8d2a48bcc40f4535d5f",
          "md5": "e5c3c396aa291fecbe6541dd6eb5f7bf"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.klib",
          "url": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.klib",
          "size": 479614,
          "sha512": "59a1255d4481c2a665efd84d3790d9f197f615309aeeb82214a99c204ebb18f0fede0f7f7de1eba342e90a7a54355a5e5f91ea191c53e3ffb346acc461cc2974",
          "sha256": "c5bc531d22fef8eb6838a151ad571b617d283fdef6079d2812c8d17c2b3d96d2",
          "sha1": "9e30a81cf89a9533bfb4d8d2a48bcc40f4535d5f",
          "md5": "e5c3c396aa291fecbe6541dd6eb5f7bf"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT-sources.jar",
          "size": 184545,
          "sha512": "842d086229c1e7f602330055ae333951752f12b2012598de19ae7c5a3737ac65c1e5bcee290ab95c1716e043f6331d43c0b3416472ac5c1e6260c0f7d5545841",
          "sha256": "2285308f402457329e2a5bd1440eeb10ddf97dccbd22cbb0b86d64863bc528c6",
          "sha1": "a6e3f8ebeb497b0db1d2c50aa3c89f7064970c08",
          "md5": "f7799755379570e48d0522beb559ee53"
        }
      ]
    }
  ]
}
