{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-2.7.6-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.klib",
          "url": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.klib",
          "size": 479506,
          "sha512": "c836e6b22173a57250c2afc5b49e28eba75af2a19e1074ce7e6d1ae36ad40314d09ae7198e69a80541d24c08a2aac25a329f96ae6f6101f0ba011ddc7c290166",
          "sha256": "77f43841a90e86586500c4a89fe1da20ff94e4fc1e7b02d0bf3058f84e0e1531",
          "sha1": "0be33fb321a12bb34fe7dffc0897cb47e04356a7",
          "md5": "2386ec3f0d13d904d7c71ca04b51bfc6"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.klib",
          "url": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.klib",
          "size": 479506,
          "sha512": "c836e6b22173a57250c2afc5b49e28eba75af2a19e1074ce7e6d1ae36ad40314d09ae7198e69a80541d24c08a2aac25a329f96ae6f6101f0ba011ddc7c290166",
          "sha256": "77f43841a90e86586500c4a89fe1da20ff94e4fc1e7b02d0bf3058f84e0e1531",
          "sha1": "0be33fb321a12bb34fe7dffc0897cb47e04356a7",
          "md5": "2386ec3f0d13d904d7c71ca04b51bfc6"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT-sources.jar",
          "size": 184531,
          "sha512": "3b234279c47f32b9e82486388ccca6410f53200713440a98e42c27df4c7197dca7dad3bd91491691086d5a9ac79ddeced3a51ab371187ba6a68adb96f6c953a4",
          "sha256": "5ba2499a3fc14440842e0bfa0f593c919e9b0aa76856f5d92b9cab7f2c9745ef",
          "sha1": "cfad72f6ae2fa1f6356717ad99ed864b585751d2",
          "md5": "8ad7d567b6b1e928b8d0811ed57ea718"
        }
      ]
    }
  ]
}
