{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-2.7.6-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.klib",
          "url": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.klib",
          "size": 479495,
          "sha512": "2f04f3a071fa8c3ea1aa93ac2a76f28b48b1e147daf042f9bcc373a3b73b43f9b13a9e0a93ab5469504058e600966be460ee9d65610b549e786b9ab1a41d68df",
          "sha256": "14312fa271e1868903a149d0950b240d6d14f62c5fbc3be4615f5ccd1f41b34c",
          "sha1": "3ef87246408c9d83eeece2a1f8453e2776b350be",
          "md5": "28e9b47b17a50a652ea911dc1f300ae3"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.klib",
          "url": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.klib",
          "size": 479495,
          "sha512": "2f04f3a071fa8c3ea1aa93ac2a76f28b48b1e147daf042f9bcc373a3b73b43f9b13a9e0a93ab5469504058e600966be460ee9d65610b549e786b9ab1a41d68df",
          "sha256": "14312fa271e1868903a149d0950b240d6d14f62c5fbc3be4615f5ccd1f41b34c",
          "sha1": "3ef87246408c9d83eeece2a1f8453e2776b350be",
          "md5": "28e9b47b17a50a652ea911dc1f300ae3"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT-sources.jar",
          "size": 184521,
          "sha512": "fa1608cd6d393af3b3874c788e370c39637e7ab06c3613a4741e4d24a2d25d6a1c97c82b3091e1dda5a4edfb36da6b23f4096d884b4485cba32ade639f69a6aa",
          "sha256": "3bceedc323bcb273b80dfaddbdc0e1ecdfbeaa5c52a7b640b2ba223472f680e1",
          "sha1": "654a432a2e684910f93266f7c1f5c04a81dd178b",
          "md5": "a8c0ffd2b0a2caadd7e04664721665fe"
        }
      ]
    }
  ]
}
