{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-2.7.6-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.klib",
          "url": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.klib",
          "size": 483052,
          "sha512": "c87d5e128730586f3ba01edc5e3491f23c1e1a30ff8f0e459c8e69c07316bf4f33e40a047991b655cd2f9af53a23e690b88fad9ef00e3d5ed790afd74fdafd4a",
          "sha256": "bba55ec737557fde4dcbe344016472a8502dec17a161d9501ee26bcfee3e6698",
          "sha1": "2830487d8a49f564b441c9f7f0ef5c32aa0b167e",
          "md5": "218eb9ee842b2f00650f525861ec3165"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.klib",
          "url": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.klib",
          "size": 483052,
          "sha512": "c87d5e128730586f3ba01edc5e3491f23c1e1a30ff8f0e459c8e69c07316bf4f33e40a047991b655cd2f9af53a23e690b88fad9ef00e3d5ed790afd74fdafd4a",
          "sha256": "bba55ec737557fde4dcbe344016472a8502dec17a161d9501ee26bcfee3e6698",
          "sha1": "2830487d8a49f564b441c9f7f0ef5c32aa0b167e",
          "md5": "218eb9ee842b2f00650f525861ec3165"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT-sources.jar",
          "size": 186572,
          "sha512": "28262180ebd5e27e00b21760d005fcdc46ca50d1174ecf5646b8e477953aa3ded8c07f46ddcbd00a94a13280c1534604fa579f5c40a25ab0a30ebad3022beaa6",
          "sha256": "d8e13dd6673ed251f860fc877caefc109d7e740fa603397a7e10ca2935b002d6",
          "sha1": "22e6352d4027f4e9a766d38598550906f78cbbd5",
          "md5": "ae617348f6bbd7cad6ead5af7fb6c630"
        }
      ]
    }
  ]
}
