{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-2.7.6-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.klib",
          "url": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.klib",
          "size": 482223,
          "sha512": "86ba0f988e68a0cde0d66d45eef095bcd47901010f279f70b73e29473834f81d98807c9f534775279cff2002a2779aa9e5dc9cb280f3e2cf66b9400db721a175",
          "sha256": "2d38e1a7210b10ebdbcbc2625800966e32bf9a5b9ac27abb583f463fd9a6b385",
          "sha1": "01bf02408455a36070f5ce3d886eb19ef28dc94c",
          "md5": "244349dabaed6221e826c24d26397e3c"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.klib",
          "url": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.klib",
          "size": 482223,
          "sha512": "86ba0f988e68a0cde0d66d45eef095bcd47901010f279f70b73e29473834f81d98807c9f534775279cff2002a2779aa9e5dc9cb280f3e2cf66b9400db721a175",
          "sha256": "2d38e1a7210b10ebdbcbc2625800966e32bf9a5b9ac27abb583f463fd9a6b385",
          "sha1": "01bf02408455a36070f5ce3d886eb19ef28dc94c",
          "md5": "244349dabaed6221e826c24d26397e3c"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT-sources.jar",
          "size": 185070,
          "sha512": "c1502af5afd89b0d93efa15d29e0afb7acd38d2aabe89736eb0577caaf0aa12aa08283d8f3e2e15ea35b463da18d84da2019a9ec63775f6dc04daa0db474726a",
          "sha256": "73462c2fb5d9e49f69201ed03883728765f2a0bdf43783c17fb10d392e20e1dc",
          "sha1": "5b9e5b5e570ebf08f18db1f84649b68a5a3bb79c",
          "md5": "1172424a54801d93f9f945536403139f"
        }
      ]
    }
  ]
}
