{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-2.7.6-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.klib",
          "url": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.klib",
          "size": 486965,
          "sha512": "2ef9aed0945c12b5846185fc70b52bfd8533c1cfc899040309be27b9a8016f440dce5a55236707d7b72d7fada279ec45d4544239778a4fbdaf814ac3a00948db",
          "sha256": "ea790d0148c7e0d1073b1a697ab9ed7591b56e3a22b8d330f322821c82809a56",
          "sha1": "9689cb59b203a74443d1c25f358b0b3f83a9613e",
          "md5": "fa638bc642c5f61d0b880a88e56196be"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.klib",
          "url": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.klib",
          "size": 486965,
          "sha512": "2ef9aed0945c12b5846185fc70b52bfd8533c1cfc899040309be27b9a8016f440dce5a55236707d7b72d7fada279ec45d4544239778a4fbdaf814ac3a00948db",
          "sha256": "ea790d0148c7e0d1073b1a697ab9ed7591b56e3a22b8d330f322821c82809a56",
          "sha1": "9689cb59b203a74443d1c25f358b0b3f83a9613e",
          "md5": "fa638bc642c5f61d0b880a88e56196be"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT-sources.jar",
          "size": 186572,
          "sha512": "28262180ebd5e27e00b21760d005fcdc46ca50d1174ecf5646b8e477953aa3ded8c07f46ddcbd00a94a13280c1534604fa579f5c40a25ab0a30ebad3022beaa6",
          "sha256": "d8e13dd6673ed251f860fc877caefc109d7e740fa603397a7e10ca2935b002d6",
          "sha1": "22e6352d4027f4e9a766d38598550906f78cbbd5",
          "md5": "ae617348f6bbd7cad6ead5af7fb6c630"
        }
      ]
    }
  ]
}
