{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-2.7.6-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.klib",
          "url": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.klib",
          "size": 487772,
          "sha512": "c26e07e42d5ba36047cd5f3e849dc9ed4a2554a175e36a8ccb858bead4e5cbc9f8614979793c5ceb1b5a975d9c1099f343d7f9083c8d0e04c0f0989f7bc00ef1",
          "sha256": "6d9f0fb8e7461efb99d1d06e70789fb58ff45efee2b57a105bae07177fbdf77c",
          "sha1": "50dbb96e436946b159acfba71d54fcbcaec442c2",
          "md5": "386c70fa65cfdd9dfb22aad5bbe2669f"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.klib",
          "url": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT.klib",
          "size": 487772,
          "sha512": "c26e07e42d5ba36047cd5f3e849dc9ed4a2554a175e36a8ccb858bead4e5cbc9f8614979793c5ceb1b5a975d9c1099f343d7f9083c8d0e04c0f0989f7bc00ef1",
          "sha256": "6d9f0fb8e7461efb99d1d06e70789fb58ff45efee2b57a105bae07177fbdf77c",
          "sha1": "50dbb96e436946b159acfba71d54fcbcaec442c2",
          "md5": "386c70fa65cfdd9dfb22aad5bbe2669f"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-js-2.7.6-SNAPSHOT-sources.jar",
          "size": 186798,
          "sha512": "a9877ee99ae815b316d7b2f7189996a91308c5a1d7a6c2212a2265a470042f13dcef45e62b75be848b95297f815c54040e2ba086c3c2cc9d1c9ddf559cf3c7c3",
          "sha256": "1d36b983d47bebeabf8ef8c2c5eac8feab79e0106023bedb4e22cb778b2df648",
          "sha1": "78d2a11326e936b8c747f46764226c73b4a08945",
          "md5": "7f008966305e24c6da7a6698fc785c8e"
        }
      ]
    }
  ]
}
