{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/3.0.0/snakeyaml-engine-kmp-3.0.0.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-3.0.0.klib",
          "url": "snakeyaml-engine-kmp-js-3.0.0.klib",
          "size": 485626,
          "sha512": "9537abf4e67e08bdf26ab4fcfa89dae13b1ac9e22802f3c971a0679a888fff73744680c896acc37c7d435225def609f77b862210e9f0a732dabb7895f93ddfb0",
          "sha256": "809eb68a912e3f99ee4a63082bd835260b69fb5f0f360579fbb0df1da97c63a5",
          "sha1": "98fb5005436ed3ed3d2bbdfcd779f0763d1e118d",
          "md5": "f9f47a5d027f96613a01a19f397ab743"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-3.0.0.klib",
          "url": "snakeyaml-engine-kmp-js-3.0.0.klib",
          "size": 485626,
          "sha512": "9537abf4e67e08bdf26ab4fcfa89dae13b1ac9e22802f3c971a0679a888fff73744680c896acc37c7d435225def609f77b862210e9f0a732dabb7895f93ddfb0",
          "sha256": "809eb68a912e3f99ee4a63082bd835260b69fb5f0f360579fbb0df1da97c63a5",
          "sha1": "98fb5005436ed3ed3d2bbdfcd779f0763d1e118d",
          "md5": "f9f47a5d027f96613a01a19f397ab743"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-js-3.0.0-sources.jar",
          "url": "snakeyaml-engine-kmp-js-3.0.0-sources.jar",
          "size": 188512,
          "sha512": "46774a50d232bd1b6276877b2759c229e1a40652ead49d39cba06047315db9bede12307b16a453e6b40a6bf1c19475118b000776cc3cf60d09a8b968a1c63a3b",
          "sha256": "f8fed099b47e152420c231134cc99c46a304ee13c001b6069c5b9d1ba8478f78",
          "sha1": "05285dc93c8a4638004599218fcd8543f8fd0b43",
          "md5": "17107c8b9dad75cfad423eea71d1c9e7"
        }
      ]
    }
  ]
}
