{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7.1-SNAPSHOT/snakeyaml-engine-kmp-2.7.1-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp.klib",
          "url": "snakeyaml-engine-kmp-mingwx64-2.7.1-SNAPSHOT.klib",
          "size": 410433,
          "sha512": "c3671090f5eee3098d3912ecb3ac796629cb255efb149557c4b07c26190f974c10a93ce0968a7c8ff0fa81918fa53dc6edeb4009e0ffd10b135f38f457cae176",
          "sha256": "ac2d747a6f2127b3e1cec55ae6026bbf7687cde29a9d33447cec1ca0401793db",
          "sha1": "137283d4e508d51ccf673742ff88597d42049bdd",
          "md5": "7625630cdb714b3e368521076e6861f4"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-mingwx64-2.7.1-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-mingwx64-2.7.1-SNAPSHOT-sources.jar",
          "size": 183169,
          "sha512": "0b28a73cab717c97330248aaf9c3acfb43575c1cfb83f83ad3c2fcc3653e5e98a7fc7446ee83436d13331f96a6f9083608dc075ee4ecee8e27188eae25e7ebc7",
          "sha256": "d5074dca97d6bd3f00274576998969a858a031c253596a0460646e5e97ddb474",
          "sha1": "15ad4db0c2c916948ddec66d85fa46b075fc049d",
          "md5": "15493a2d0151b51cf415a8ee4c0e1551"
        }
      ]
    }
  ]
}
