{
  "formatVersion": "1.1",
  "component": {
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-metadata-2.7.2-SNAPSHOT.jar",
          "url": "snakeyaml-engine-kmp-2.7.2-SNAPSHOT.jar",
          "size": 53034,
          "sha512": "c7c611e2b9bba2e2d4f8cd03d5474235e47835bb3e997dd86bd37790cd463d7d4142499f7388b4f0451b4ff7fb54eaec189419dc7aaa8a8fd7c080593169bc63",
          "sha256": "e665052da6e3bc4285865af2c2952f2f77dec6f9c156ecb3269fcc20c65391f0",
          "sha1": "4251a0fb147b316d3a54ae2e5aebef292feadd6f",
          "md5": "9abccce37e4038243247ce99e453e44b"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-kotlin-2.7.2-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-2.7.2-SNAPSHOT-sources.jar",
          "size": 183189,
          "sha512": "edac3559d7b0fd1bc479a7b903f502d19e2ed43b16622213679fb299c3d9eaffd871ebae0ec76e2c18b3cd7d838bbff34a3410e9779fe9198513401ebc2ab454",
          "sha256": "7ec63c6b65790115d4151f43b7bb0e4b5f54bed7dcaccfe8be60352508ee895a",
          "sha1": "eccf25dd91938c3b9000a2f7267831bef1a6f4b2",
          "md5": "af14622db50c7a940699b2e37bdc4414"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-js/2.7.2-SNAPSHOT/snakeyaml-engine-kmp-js-2.7.2-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-js",
        "version": "2.7.2-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-js/2.7.2-SNAPSHOT/snakeyaml-engine-kmp-js-2.7.2-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-js",
        "version": "2.7.2-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-js/2.7.2-SNAPSHOT/snakeyaml-engine-kmp-js-2.7.2-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-js",
        "version": "2.7.2-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-jvm/2.7.2-SNAPSHOT/snakeyaml-engine-kmp-jvm-2.7.2-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-jvm",
        "version": "2.7.2-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-jvm/2.7.2-SNAPSHOT/snakeyaml-engine-kmp-jvm-2.7.2-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-jvm",
        "version": "2.7.2-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-jvm/2.7.2-SNAPSHOT/snakeyaml-engine-kmp-jvm-2.7.2-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-jvm",
        "version": "2.7.2-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-linuxx64/2.7.2-SNAPSHOT/snakeyaml-engine-kmp-linuxx64-2.7.2-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-linuxx64",
        "version": "2.7.2-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-linuxx64/2.7.2-SNAPSHOT/snakeyaml-engine-kmp-linuxx64-2.7.2-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-linuxx64",
        "version": "2.7.2-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosarm64/2.7.2-SNAPSHOT/snakeyaml-engine-kmp-macosarm64-2.7.2-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosarm64",
        "version": "2.7.2-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosarm64/2.7.2-SNAPSHOT/snakeyaml-engine-kmp-macosarm64-2.7.2-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosarm64",
        "version": "2.7.2-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosarm64/2.7.2-SNAPSHOT/snakeyaml-engine-kmp-macosarm64-2.7.2-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosarm64",
        "version": "2.7.2-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosx64/2.7.2-SNAPSHOT/snakeyaml-engine-kmp-macosx64-2.7.2-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosx64",
        "version": "2.7.2-SNAPSHOT"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosx64/2.7.2-SNAPSHOT/snakeyaml-engine-kmp-macosx64-2.7.2-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosx64",
        "version": "2.7.2-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-macosx64/2.7.2-SNAPSHOT/snakeyaml-engine-kmp-macosx64-2.7.2-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-macosx64",
        "version": "2.7.2-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-mingwx64/2.7.2-SNAPSHOT/snakeyaml-engine-kmp-mingwx64-2.7.2-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-mingwx64",
        "version": "2.7.2-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../snakeyaml-engine-kmp-mingwx64/2.7.2-SNAPSHOT/snakeyaml-engine-kmp-mingwx64-2.7.2-SNAPSHOT.module",
        "group": "it.krzeminski",
        "module": "snakeyaml-engine-kmp-mingwx64",
        "version": "2.7.2-SNAPSHOT"
      }
    }
  ]
}
