{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7.2-SNAPSHOT/snakeyaml-engine-kmp-2.7.2-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp.klib",
          "url": "snakeyaml-engine-kmp-macosarm64-2.7.2-SNAPSHOT.klib",
          "size": 437403,
          "sha512": "c1f5e6009ab26755ba72f137a424d58923ad0e2a6a6200ee3801fb988664a697923cdb463772ee53e91657418bcc249cd2bffef899b4c2acd5f9e093cc288237",
          "sha256": "172d288db589ffce0c16ab3a4c2f5fadc1d41316b35fb28516f0fdb3daeea228",
          "sha1": "eee9214ab6953205e260b314c05abbdd8a0e89fd",
          "md5": "8b9deef05f10d37c0758a7298a1e4bf9"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-macosarm64-2.7.2-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-macosarm64-2.7.2-SNAPSHOT-sources.jar",
          "size": 183205,
          "sha512": "c5c686632fc9f1c22c6774898621efa81ac79db6660ee752c8c3d6a4e266679930cc6cdeb954f52a786fc0f4d04ecbe882103e73848f3edd0bd74e019d3e1248",
          "sha256": "120fe87d901e146486a7363ef932f6d47771c9ea3623ae607befc1fe7d03c34c",
          "sha1": "c2516305ce3602b918af211b2a3b3a27df95dcf5",
          "md5": "fb8e2f9d55cbd16d03ea35181e4dade4"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-macosarm64-2.7.2-SNAPSHOT-metadata.jar",
          "url": "snakeyaml-engine-kmp-macosarm64-2.7.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
