{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/3.0.2-SNAPSHOT/snakeyaml-engine-kmp-3.0.2-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "3.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-wasm-js-3.0.2-SNAPSHOT.klib",
          "url": "snakeyaml-engine-kmp-wasm-js-3.0.2-SNAPSHOT.klib",
          "size": 491654,
          "sha512": "4b2a4a4bd028f6e12d9a485608d37297e4d87fc7acac9a2d98f1ff1f79f1ae8a9825a995ec4e45321417846ff80051475e733b50321104ca993c893cd87a8654",
          "sha256": "8cd42128135a5301b4032c25506d6ec1a607d3a9c2effa9c57406714f0c662d1",
          "sha1": "e4dcff348ef126a619414a5dfc2f35dbad9369b0",
          "md5": "ced86547dfe8056ae4730b93fe6da88f"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-wasm-js-3.0.2-SNAPSHOT.klib",
          "url": "snakeyaml-engine-kmp-wasm-js-3.0.2-SNAPSHOT.klib",
          "size": 491654,
          "sha512": "4b2a4a4bd028f6e12d9a485608d37297e4d87fc7acac9a2d98f1ff1f79f1ae8a9825a995ec4e45321417846ff80051475e733b50321104ca993c893cd87a8654",
          "sha256": "8cd42128135a5301b4032c25506d6ec1a607d3a9c2effa9c57406714f0c662d1",
          "sha1": "e4dcff348ef126a619414a5dfc2f35dbad9369b0",
          "md5": "ced86547dfe8056ae4730b93fe6da88f"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-wasm-js-3.0.2-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-wasm-js-3.0.2-SNAPSHOT-sources.jar",
          "size": 191163,
          "sha512": "0bad5e5ccce205c1014b96c6367eb0cea3099e751d297ac6f467920a244d8e98a9d1a8e20b1cab5fe4bcb05fb75ac33a00f8c1ee5f3721541c967e168a7794ff",
          "sha256": "a3fabb3307ed46e03ee1c67cd939f37c199ad879e758c6724fe03b24acf9af4b",
          "sha1": "4acc1c405b7b6cc96479a874969e4df40b14bb3c",
          "md5": "f060680ed28147c60a9f1f1cf436e713"
        }
      ]
    }
  ]
}
