{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7.4-SNAPSHOT/snakeyaml-engine-kmp-2.7.4-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp.klib",
          "url": "snakeyaml-engine-kmp-iossimulatorarm64-2.7.4-SNAPSHOT.klib",
          "size": 424753,
          "sha512": "59f3d1ebd881225e134ce601ee0c637a80e9ac5a0b56de71a8ef14ee697789c1b5abad58ffca867fa2853f0a61aaee800e75548a3e4dd3c77721f4b568b0513e",
          "sha256": "6b98471edee6c8a70d1f68e218e7babe2f9ccd3ffd1cb5bb88734c8304cf9283",
          "sha1": "10b27ce0003219bec8a03e45e34e9cdc65f5a0ae",
          "md5": "a1f6d4e26ed47c8f5ca66f06ebb9afd1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-iossimulatorarm64-2.7.4-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-iossimulatorarm64-2.7.4-SNAPSHOT-sources.jar",
          "size": 179000,
          "sha512": "f9c5792671ff61ca6b7f39f31915556edb8e89a44b91d9d38b63901fe0120ae737de3e0527b8e7aed8486b324ce609231e0bf522f8c32f87a758a02d4672cab1",
          "sha256": "8d6efe1214de15d6b48aa0afd8c4da6aefb65d83f41ebaecae984bc10952edc3",
          "sha1": "3c5b2837544c0cea85a90dab7ba4c8e1427efba4",
          "md5": "c530d843a9377f83dc428e2c28d50e90"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp-iossimulatorarm64-2.7.4-SNAPSHOT-metadata.jar",
          "url": "snakeyaml-engine-kmp-iossimulatorarm64-2.7.4-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
