{
  "formatVersion": "1.1",
  "component": {
    "url": "../../snakeyaml-engine-kmp/2.7.6-SNAPSHOT/snakeyaml-engine-kmp-2.7.6-SNAPSHOT.module",
    "group": "it.krzeminski",
    "module": "snakeyaml-engine-kmp",
    "version": "2.7.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        },
        {
          "group": "net.thauvin.erik.urlencoder",
          "module": "urlencoder-lib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "snakeyaml-engine-kmp.klib",
          "url": "snakeyaml-engine-kmp-linuxarm64-2.7.6-SNAPSHOT.klib",
          "size": 489128,
          "sha512": "8be40245b12c01a5d36659f9477a7ab88a24a6d8969eaeba7a11e9418bf401e51ac0248cba79283d80ceca6c31e050bc252a5fb3b0ad800eaefe00160accad06",
          "sha256": "125c30fecd20c127262cf6d00380f14f5d57b852bdeaca9fdbf9451e9db9d682",
          "sha1": "855b99c93d272afaf787c827a40f20fe2e7f600a",
          "md5": "d659c8bc98932ca1eb9259850084645e"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "snakeyaml-engine-kmp-linuxarm64-2.7.6-SNAPSHOT-sources.jar",
          "url": "snakeyaml-engine-kmp-linuxarm64-2.7.6-SNAPSHOT-sources.jar",
          "size": 186945,
          "sha512": "9d777eac962acc5b42cbf8872d1b5b2008e0b4eda2dd35272ced3e74b034dae03f31fc081b31da6f3d59d6d30f1d691af0b76a9c8884e8e40099baa90cc66829",
          "sha256": "4673b3dfe73e9b9632c7ec9ef631d025e575076e46a048aa22a1f6d21be0b84b",
          "sha1": "1cafc9319553f9940c7f19ea057bef7b98fc7e2a",
          "md5": "fdbc2d8b7f6bb8aa3631a06153c1c0a6"
        }
      ]
    }
  ]
}
